export const mockProducts = [
  {
    id: "E481044-000",
    brand: "B:C",
    name: "블록테크 파카",
    price: 149000,
    rating: 5.0,
    ratingCount: 11,
    is_available: true,
    colors: [
      { code: "09", name: "Black", hex: "#111111" },
      { code: "39", name: "Dark Brown", hex: "#4b3a33" },
      { code: "57", name: "Olive", hex: "#3a4a3d" },
    ],
    sizes: ["M", "L", "XL"],
    gallery: [
      "https://placehold.co/600x400?text=outer1",
      "https://placehold.co/600x400?text=outer2",
    ],
    details: [
      { img: "https://placehold.co/600x400?text=outer-detail1", text: "방풍/발수 기능으로 아웃도어 커버" },
      { img: "https://placehold.co/600x400?text=outer-detail2", text: "실용적인 포켓과 미니멀 실루엣" },
    ],
    material: ["폴리에스터 100%"],
    care: ["세탁기 사용 가능 (망 권장)", "표백제 금지"],
    gender: "men",
    category: "outer",
    created_at: "2025-09-01",
  },
  {
    id: "TSHIRT-100",
    brand: "UniQ",
    name: "화이트 라운드 티셔츠",
    price: 19000,
    rating: 4.5,
    ratingCount: 87,
    is_available: true,
    colors: [
      { code: "01", name: "White", hex: "#ffffff" },
      { code: "09", name: "Black", hex: "#000000" },
    ],
    sizes: ["S", "M", "L", "XL"],
    gallery: [
      "https://placehold.co/600x400?text=tshirt1",
      "https://placehold.co/600x400?text=tshirt2",
    ],
    details: [
      { img: "https://placehold.co/600x400?text=tshirt-detail1", text: "데일리 필수 라운드넥 티셔츠" },
    ],
    material: ["면 100%"],
    care: ["세탁기 사용 가능", "건조기 금지"],
    gender: "unisex",
    category: "top",
    created_at: "2025-08-25",
  },
  {
    id: "JEANS-200",
    brand: "DenimX",
    name: "슬림 핏 진",
    price: 59000,
    rating: 4.2,
    ratingCount: 45,
    is_available: false,
    colors: [
      { code: "69", name: "Dark Blue", hex: "#223344" },
      { code: "68", name: "Light Blue", hex: "#5a7fa3" },
    ],
    sizes: ["28", "30", "32", "34"],
    gallery: [
      "https://placehold.co/600x400?text=jeans1",
      "https://placehold.co/600x400?text=jeans2",
    ],
    details: [
      { img: "https://placehold.co/600x400?text=jeans-detail1", text: "슬림핏으로 다리가 길어 보이는 효과" },
    ],
    material: ["면 98%", "엘라스틴 2%"],
    care: ["찬물 단독 세탁", "표백제 금지"],
    gender: "men",
    category: "bottom",
    created_at: "2025-08-15",
  },
  {
    id: "ACC-300",
    brand: "DailyBag",
    name: "캔버스 토트백",
    price: 39000,
    rating: 4.7,
    ratingCount: 23,
    is_available: true,
    colors: [
      { code: "30", name: "Beige", hex: "#e6d7c3" },
      { code: "09", name: "Black", hex: "#000000" },
    ],
    sizes: ["Free"],
    gallery: [
      "https://placehold.co/600x400?text=bag1",
    ],
    details: [
      { img: "https://placehold.co/600x400?text=bag-detail1", text: "튼튼한 캔버스 원단 사용" },
    ],
    material: ["면 100%"],
    care: ["손세탁 권장", "표백제 금지"],
    gender: "unisex",
    category: "acc",
    created_at: "2025-07-30",
  },
  {
    id: "ONEP-400",
    brand: "Femina",
    name: "플라워 원피스",
    price: 89000,
    rating: 4.9,
    ratingCount: 64,
    is_available: true,
    colors: [
      { code: "20", name: "Pink", hex: "#f5a6c7" },
      { code: "40", name: "Sky Blue", hex: "#8ecae6" },
    ],
    sizes: ["S", "M", "L"],
    gallery: [
      "https://placehold.co/600x400?text=onepiece1",
    ],
    details: [
      { img: "https://placehold.co/600x400?text=onepiece-detail1", text: "여성스러운 플라워 패턴" },
    ],
    material: ["폴리에스터 70%", "면 30%"],
    care: ["드라이클리닝 권장"],
    gender: "women",
    category: "dress",
    created_at: "2025-08-10",
  },
];
